name: Deploy NestJS to EC2 Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          # Prerequisites: Docker installed & EC2 user added to docker group
          sudo systemctl start docker
          sudo systemctl enable docker

          # Ensure GitHub is trusted
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          cd ~/my-nest-api || git clone https://github.com/argentra-kumar/aws-cicd.git ~/my-nest-api && cd ~/my-nest-api

          git pull origin main

          # Stop and remove existing container if exists
          docker stop nest-api || true
          docker rm nest-api || true

          # Remove old image (optional cleanup)
          docker rmi nest-api || true

          # Build with Yarn and Node 22
          docker build -t nest-api .

          # Run container
          docker run -d --name nest-api -p 3000:3000 nest-api
        EOF
